### ISSUE TITLE
Fails with MooX-ClassAttribute > 0.008

### ISSUE THREAD

**Issue by andk** [SineSwiper/Parse-Path#1]
As per subject. Downgrading to TOBYINK/MooX-ClassAttribute-0.008.tar.gz makes tests pass.

Sample fail report with 0.009:
http://www.cpantesters.org/cpan/report/33852917

HTH && Regards,

**Comment by SineSwiper** [comment]
Fails with .010, too.  I might just remove the class attribute altogether.  They seem to be too magical.

**Comment by SineSwiper** [comment]
Fixed in 0.92.
